"""TAS librarian — the sole sanctioned writer to ``TAS/data/*.ndjson``.

v0.1 surfaces only the concurrency primitives ported from Proteus
(``safe_access`` module).  Future revisions will add the fetcher,
the Digi-Key / Mouser API wrappers, and the auditor — each behind
its own explicit import so this package's import-time footprint
stays minimal.
"""

from __future__ import annotations

from heaviside.librarian.safe_access import (
    CATEGORIES,
    LOCK_DIR,
    TAS_DATA_DIR,
    LibrarianError,
    LockTimeoutError,
    Transaction,
    UnknownCategoryError,
    acquire_lock,
    describe_lock,
    safe_append,
)
from heaviside.librarian.tas import (
    SCHEMA_MAP,
    DuplicateComponentError,
    SchemaNotFoundError,
    ValidationError,
    add_component,
    component_exists,
    load_validator,
    validate_component,
)
from heaviside.librarian.auditor import (
    AUDITABLE_CATEGORIES,
    CRITICAL_PARAMS,
    REQUIRED_PARAMS,
    CategoryAudit,
    ComponentAudit,
    CorruptLine,
    FieldGap,
    FieldStatus,
    audit_all,
    audit_category,
    audit_component,
)
from heaviside.librarian.datasheet import (
    CATEGORY_PATTERNS,
    DEFAULT_CACHE_DIR,
    DatasheetDownloadError,
    DatasheetError,
    DatasheetParseError,
    DatasheetReader,
    IncompleteDatasheetError,
    MissingDependencyError,
    PdfCache,
    REQUIRED_BY_CATEGORY,
    extract_params,
    extract_required_params,
    extract_tables,
)
from heaviside.librarian.fetcher import (    DIGIKEY_PROD_BASE,
    DIGIKEY_SANDBOX_BASE,
    MOUSER_API_BASE,
    STAGING_DIR,
    CredentialError,
    Credentials,
    DigiKeyClient,
    DigiKeyCredentials,
    DistributorError,
    FetcherError,
    IncompleteSourceError,
    MalformedResponseError,
    MissingCredentialError,
    MouserClient,
    MouserCredentials,
    RateLimitError,
    StagedRecord,
    StagingError,
    TokenCache,
    apply_staged,
    convert_digikey_to_tas_capacitor,
    convert_digikey_to_tas_diode,
    convert_digikey_to_tas_igbt,
    convert_digikey_to_tas_mosfet,
    convert_digikey_to_tas_resistor,
    convert_mouser_to_tas_capacitor,
    convert_mouser_to_tas_diode,
    convert_mouser_to_tas_igbt,
    convert_mouser_to_tas_mosfet,
    convert_mouser_to_tas_resistor,
    list_staged,
    load_credentials,
    parse_si_value,
    stage_fetch,
)

__all__ = [
    "AUDITABLE_CATEGORIES",
    "CATEGORIES",
    "CATEGORY_PATTERNS",
    "CRITICAL_PARAMS",
    "CategoryAudit",
    "ComponentAudit",
    "CorruptLine",
    "CredentialError",
    "Credentials",
    "DEFAULT_CACHE_DIR",
    "DIGIKEY_PROD_BASE",
    "DIGIKEY_SANDBOX_BASE",
    "DatasheetDownloadError",
    "DatasheetError",
    "DatasheetParseError",
    "DatasheetReader",
    "DigiKeyClient",
    "DigiKeyCredentials",
    "DistributorError",
    "DuplicateComponentError",
    "FetcherError",
    "FieldGap",
    "FieldStatus",
    "IncompleteDatasheetError",
    "IncompleteSourceError",
    "LOCK_DIR",
    "LibrarianError",
    "LockTimeoutError",
    "MOUSER_API_BASE",
    "MalformedResponseError",
    "MissingCredentialError",
    "MissingDependencyError",
    "MouserClient",
    "MouserCredentials",
    "PdfCache",
    "REQUIRED_BY_CATEGORY",
    "REQUIRED_PARAMS",
    "RateLimitError",
    "SCHEMA_MAP",
    "SchemaNotFoundError",
    "STAGING_DIR",
    "StagedRecord",
    "StagingError",
    "TAS_DATA_DIR",
    "TokenCache",
    "Transaction",
    "UnknownCategoryError",
    "ValidationError",
    "acquire_lock",
    "add_component",
    "apply_staged",
    "audit_all",
    "audit_category",
    "audit_component",
    "component_exists",
    "convert_digikey_to_tas_capacitor",
    "convert_digikey_to_tas_diode",
    "convert_digikey_to_tas_igbt",
    "convert_digikey_to_tas_mosfet",
    "convert_digikey_to_tas_resistor",
    "convert_mouser_to_tas_capacitor",
    "convert_mouser_to_tas_diode",
    "convert_mouser_to_tas_igbt",
    "convert_mouser_to_tas_mosfet",
    "convert_mouser_to_tas_resistor",
    "describe_lock",
    "extract_params",
    "extract_required_params",
    "extract_tables",
    "list_staged",
    "load_credentials",
    "parse_si_value",
    "safe_append",
    "stage_fetch",
    "validate_component",
]
