"""``heaviside.topologies.flyback`` — thin dispatch wrapper.

Auto-generated by ``scripts/gen_topology_modules.py`` from the registry.
Do not edit by hand; edit ``heaviside/topologies/registry.py`` and regenerate.

Kind:        ``converter``
Family:      ``isolated_single_switch``
MAS schema:  ``MAS/schemas/inputs/topologies/flyback.json``
PyOM names:  ``['flyback']``
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from heaviside.topologies.dispatch import ProcessConverterResult
from heaviside.topologies.dispatch import design as _dispatch
from heaviside.topologies.registry import get

ENTRY = get("flyback")


def design(
    converter_json: Mapping[str, Any], *, use_ngspice: bool = True
) -> ProcessConverterResult:
    """Design a isolated_single_switch ``flyback`` converter via PyOpenMagnetics.

    See :func:`heaviside.topologies.dispatch.design` for full semantics.
    """
    return _dispatch(ENTRY, converter_json, use_ngspice=use_ngspice)
