"""``heaviside.topologies.isolated_buck_boost`` — thin dispatch wrapper.

Auto-generated by ``scripts/gen_topology_modules.py`` from the registry.
Do not edit by hand; edit ``heaviside/topologies/registry.py`` and regenerate.

Kind:        ``converter``
Family:      ``isolated_single_switch``
MAS schema:  ``MAS/schemas/inputs/topologies/isolatedBuckBoost.json``
PyOM names:  ``['isolatedBuckBoost']``
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from heaviside.topologies.dispatch import ProcessConverterResult
from heaviside.topologies.dispatch import design as _dispatch
from heaviside.topologies.registry import get

ENTRY = get("isolated_buck_boost")


def design(
    converter_json: Mapping[str, Any], *, use_ngspice: bool = True
) -> ProcessConverterResult:
    """Design a isolated_single_switch ``isolated_buck_boost`` converter via PyOpenMagnetics.

    See :func:`heaviside.topologies.dispatch.design` for full semantics.
    """
    return _dispatch(ENTRY, converter_json, use_ngspice=use_ngspice)
