#!/usr/bin/env python3
"""Generate one thin ``heaviside/topologies/<name>.py`` module per registry entry.

Run with: ``python scripts/gen_topology_modules.py``

The generated modules are checked into git (they are stable, hand-readable,
and ≤ 30 LOC each). Regenerating overwrites them; do not edit by hand —
edit the registry instead.
"""

from __future__ import annotations

from pathlib import Path

from heaviside.topologies.registry import TOPOLOGIES, TopologyEntry

ROOT = Path(__file__).resolve().parents[1] / "heaviside" / "topologies"

TEMPLATE = '''\
"""``heaviside.topologies.{name}`` — thin dispatch wrapper.

Auto-generated by ``scripts/gen_topology_modules.py`` from the registry.
Do not edit by hand; edit ``heaviside/topologies/registry.py`` and regenerate.

Kind:        ``{kind}``
Family:      ``{family}``
MAS schema:  ``MAS/schemas/inputs/topologies/{mas_schema}.json``
PyOM names:  ``{pyom_names}``
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from heaviside.topologies.dispatch import ProcessConverterResult
from heaviside.topologies.dispatch import design as _dispatch
from heaviside.topologies.registry import get

ENTRY = get({name!r})


def design(
    converter_json: Mapping[str, Any], *, use_ngspice: bool = True
) -> ProcessConverterResult:
    """Design a {family} ``{name}`` converter via PyOpenMagnetics.

    See :func:`heaviside.topologies.dispatch.design` for full semantics.
    """
    return _dispatch(ENTRY, converter_json, use_ngspice=use_ngspice)
'''


def render(entry: TopologyEntry) -> str:
    return TEMPLATE.format(
        name=entry.name,
        kind=entry.kind,
        family=entry.family,
        mas_schema=entry.mas_schema,
        pyom_names=list(entry.pyom_names),
    )


def main() -> None:
    written = 0
    for entry in TOPOLOGIES:
        path = ROOT / f"{entry.name}.py"
        path.write_text(render(entry))
        written += 1
    print(f"Wrote {written} topology modules to {ROOT}")


if __name__ == "__main__":
    main()
